version: '3.8'

services:

  punto_fijo:
    build: ./Microservices/PuntoFijo
    container_name: metodo_punto_fijo
    ports:
      - "5001:5000"
    volumes:
      - ./Microservices/PuntoFijo:/app
    restart: always
    
  biseccion:
    build: ./Microservices/Biseccion
    container_name: metodo_biseccion
    ports:
      - "5002:5000"
    volumes:
      - ./Microservices/Biseccion:/app
    restart: always

  newton_raphson:
    build: ./Microservices/NewtonRaphson
    container_name: metodo_newton_raphson
    ports:
      - "5003:5000"
    volumes:
      - ./Microservices/NewtonRaphson:/app
    restart: always

  secante:
    build: ./Microservices/Secante
    container_name: metodo_secante
    ports:
      - "5004:5000"
    volumes:
      - ./Microservices/Secante:/app
    restart: always

  jacobi:
    build: ./Microservices/Jacobi
    container_name: metodo_jacobi
    ports:
      - "5005:5000"
    volumes:
      - ./Microservices/Jacobi:/app
    restart: always

  gauss_seidel:
    build: ./Microservices/GaussSeidel
    container_name: metodo_gauss_seidel
    ports:
      - "5006:5000"
    volumes:
      - ./Microservices/GaussSeidel:/app
    restart: always

